### ISSUE TITLE
Shed creates a `.hypothesis/` directory when run

### ISSUE THREAD

**Issue by TomFryers** [Zac-HD/shed#26]
This is a bit annoying. It doesn't seem to contain very much: just `.hypothesis/unicode_data/13.0.0/charmap.json.gz`.

**Comment by hugovk** [comment]
This is https://github.com/HypothesisWorks/hypothesis/issues/3140, fixed in hypothesis 6.28.0.

Try upgrading hypothesis? For example:

```
python -m pip install -U hypothesis
```

**Comment by TomFryers** [comment]
That doesn't seem to fix it. I think the directory appears whenever `hypothesis` is imported:
```bash
$ ls -A
$ python -c "import hypothesis;print(hypothesis.__version__)"
6.35.0
$ ls -A
.hypothesis
```

**Comment by Zac-HD** [comment]
@hugovk, it's related but a distinct issue - `shed --refactor` runs Hypothesis' codemods, which require importing Hypothesis to check the signature of various functions.

I think we can work around this by only doing so if a simple regex shows that the file being formatted actually uses Hypothesis, which should be a perf win too.
